---
- name: Connect to Win VM
  hosts: all

  vars:
    ansible_password: Pa$$w0rd!
    ansible_user: azureuser
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:

    - name: Test connection
      ansible.windows.win_ping:
